const SponsorChild = {
    InitiativeMainTextTitle: "Transformin lives, one child at a time",
    InitiativeMainTextText: "",
    InitiativeSectionOneImg: "",
    InitiativeSectionOneImgAlt: "",
    InitiativeSectionOneImgWidth: "",
    InitiativeSectionOneImgHeight: "",
    InitiativeSectionOneTitle: "Why Sponsorship?",
    InitiativeSectionOneTextBody: "",
    InitiativeSectionTwoTitle: "How we change lives",
    InitiativeSectionTwoBTNText: "Sponsor a child",
    InitiativeSectionTwoBoxTitleOne: "Choose",
    InitiativeSectionTwoBoxTextOne: "",
    InitiativeSectionTwoBoxTitleTwo: "Fund",
    InitiativeSectionTwoBoxTextTwo: "",
    InitiativeSectionTwoBoxTitleThree: "Connect",
    InitiativeSectionTwoBoxTextThree: "",
    InitiativeWhatWeDoSectionText: "",
    InitiativeWhatWeDoSectionListOne: "",
    InitiativeWhatWeDoSectionListTwo: "",
    InitiativeWhatWeDoSectionListThree: "",
    InitiativeWhatWeDoSectionImg: "",
    InitiativeWhatWeDoSectionImgAlt: "",
    InitiativeWhatWeDoSectionImgWidth: "",
    InitiativeWhatWeDoSectionImgHeight: "",
};

export default SponsorChild;